import type { Category, CityPricing, Package, Service } from './types';
import { DEFAULT_CITY_SLUG } from './city';

// Source unique de la ville par défaut : lib/city.ts (réexport compatibilité).
export { DEFAULT_CITY_SLUG };

const img = (cat: string) => `/fika/${cat}.svg`;
const seo = (title: string, desc: string) => ({
  seoTitle: `${title} à Ngaoundéré | Fika`,
  seoDescription: `${desc} Fika trouve et coordonne le bon professionnel à Ngaoundéré.`,
});

export const UNIVERSES: Category[] = [
  {
    id: 'maison-travaux',
    slug: 'maison-travaux',
    title: 'Maison & Travaux',
    description: 'Plomberie, électricité, maçonnerie, peinture, menuiserie, soudure.',
    promise: 'Construisez, réparez et rénovez sans tracas. Fika trouve et supervise les artisans qualifiés.',
    icon: 'Home',
    examples: 'Fuite d\'eau · Panne électrique · Maçonnerie · Peinture · Carrelage · Menuiserie',
    featured: true,
    color: 'bg-blue-50 text-blue-700 border-blue-200',
    active: true,
  },
  {
    id: 'reparation-maintenance',
    slug: 'reparation-maintenance',
    title: 'Réparation & Maintenance',
    description: 'Téléphones, électroménager, climatisation, informatique, matériel électrique.',
    promise: 'Ne jetez plus vos équipements. Fika diagnostique la panne et missionne le bon réparateur.',
    icon: 'Wrench',
    examples: 'Écran cassé · Frigo ou congélateur · Climatisation · Ordinateur & PC',
    featured: true,
    color: 'bg-amber-50 text-amber-700 border-amber-200',
    active: true,
  },
  {
    id: 'auto-moto',
    slug: 'auto-moto',
    title: 'Auto & Moto',
    description: 'Mécanique, électricité auto, vidange, dépannage express moto et voiture.',
    promise: 'Restez mobile. Un mécanicien ou dépanneur de confiance envoyé directement où vous êtes.',
    icon: 'Car',
    examples: 'Panne de démarrage · Vidange · Batterie à plat · Diagnostic moteur',
    featured: true,
    color: 'bg-rose-50 text-rose-700 border-rose-200',
    active: true,
  },
  {
    id: 'transport-logistique',
    slug: 'transport-logistique',
    title: 'Transport & Logistique',
    description: 'Déménagement, transport de marchandises, courses et livraisons express.',
    promise: 'Déplacez vos biens et effectuez vos courses en toute sécurité dans tout Ngaoundéré.',
    icon: 'Truck',
    examples: 'Déménagement local · Transport matériaux · Courses & Colis express',
    featured: true,
    color: 'bg-emerald-50 text-emerald-700 border-emerald-200',
    active: true,
  },
  {
    id: 'numerique-documents',
    slug: 'numerique-documents',
    title: 'Numérique & Documents',
    description: 'Bureautique, CV professionnel, impression, mise en page, création de site vitrine.',
    promise: 'Vos besoins administratifs et présence digitale gérés avec sérieux et rapidité.',
    icon: 'FileText',
    examples: 'CV & Lettre · Impression & Reliure · Saisie · Site vitrine',
    featured: true,
    color: 'bg-indigo-50 text-indigo-700 border-indigo-200',
    active: true,
  },

];

export const SERVICES: Service[] = [
  /* =======================================================================
   * 1. MAISON & TRAVAUX
   * ======================================================================= */
  {
    id: 's-mai-1',
    slug: 'intervention-plomberie',
    name: 'Dépannage Plomberie',
    categoryId: 'maison-travaux',
    shortDescription: 'Fuite d\'eau, robinet cassé, débouchage et raccordement sanitaire.',
    fullDescription: 'Une urgence ou une installation prévue ? Décrivez votre problème de plomberie. Fika sélectionne dans son réseau un plombier adapté à Ngaoundéré pour intervenir rapidement, diagnostiquer la panne et vous remettre un devis clair.',
    priceType: 'QUOTE',
    startingPrice: null,
    deliveryIncluded: false,
    estimatedDuration: 'Intervention sous 2h à 24h',
    includedItems: ['Déplacement du plombier organisé par Fika (intégré au devis)', 'Diagnostic complet de la panne', 'Devis transparent avant toute réparation'],
    excludedItems: ['Coût des pièces et raccords de rechange'],
    requirements: [
      { label: 'Décrivez précisément le problème constaté', kind: 'TEXT', required: true, position: 1 },
      { label: 'Photo ou vidéo de la fuite / canalisation', kind: 'FILE', required: false, position: 2 },
      { label: 'Quartier ou repère à Ngaoundéré', kind: 'TEXT', required: true, position: 3 },
    ],
    active: true,
    featured: true,
    popular: true,
    displayOrder: 1,
    budget: 'Faible',
    delai: 'Rapide',
    typeBesoin: 'Intervention',
    image: img('maison'),
    faqs: [
      { q: 'En combien de temps le plombier intervient-il à Ngaoundéré ?', a: 'En cas d\'urgence fuite d\'eau, l\'artisan peut intervenir en moins de 2h dans notre périmètre.' },
      { q: 'Comment est fixé le prix de l\'intervention ?', a: 'Fika ne vend pas de faux prix fixe : le professionnel diagnostique le problème sur place et un devis clair (déplacement, main-d\'œuvre et pièces) est validé avant réparation.' }
    ],
    ...seo('Dépannage Plomberie', 'Fuite d\'eau, débouchage, robinetterie à Ngaoundéré.'),
  },
  {
    id: 's-mai-2',
    slug: 'intervention-electricite',
    name: 'Dépannage Électricité',
    categoryId: 'maison-travaux',
    shortDescription: 'Court-circuit, disjoncteur qui saute, prises défectueuses et éclairage.',
    fullDescription: 'Un problème électrique exige un professionnel du métier pour votre sécurité. Décrivez votre panne, Fika mandate un électricien de son réseau pour diagnostiquer le circuit et sécuriser votre installation.',
    priceType: 'QUOTE',
    startingPrice: null,
    deliveryIncluded: false,
    estimatedDuration: 'Intervention sous 2h à 24h',
    includedItems: ['Déplacement de l\'électricien organisé par Fika (intégré au devis)', 'Diagnostic de sécurité électrique', 'Devis clair avant travaux'],
    excludedItems: ['Fourniture du matériel à remplacer (disjoncteurs, câbles)'],
    requirements: [
      { label: 'Décrivez la panne ou l\'installation demandée', kind: 'TEXT', required: true, position: 1 },
      { label: 'Quartier à Ngaoundéré', kind: 'TEXT', required: true, position: 2 },
    ],
    active: true,
    featured: true,
    popular: true,
    displayOrder: 2,
    budget: 'Faible',
    delai: 'Rapide',
    typeBesoin: 'Intervention',
    image: img('maison'),
    ...seo('Dépannage Électricité', 'Panne de courant, court-circuit et électricité générale.'),
  },
  {
    id: 's-mai-3',
    slug: 'travaux-maconnerie',
    name: 'Maçonnerie & Gros Œuvre',
    categoryId: 'maison-travaux',
    shortDescription: 'Élévation de murs, crépissage, dallage, clôtures et petites rénovations.',
    fullDescription: 'Vous avez un projet de construction ou de rénovation ? Fika vous met en relation avec des maçons expérimentés, organise la visite de chantier, calibre le devis des matériaux et suit la bonne exécution des travaux.',
    priceType: 'PROJECT',
    startingPrice: undefined,
    deliveryIncluded: false,
    estimatedDuration: 'Selon envergure du chantier',
    includedItems: ['Visite de chantier sur place', 'Métré et estimation des matériaux', 'Devis détaillé main-d\'œuvre'],
    excludedItems: ['Achat des matériaux (sable, ciment, gravier, parpaings)'],
    requirements: [
      { label: 'Nature précise des travaux à réaliser', kind: 'TEXT', required: true, position: 1 },
      { label: 'Dimensions ou superficie estimée', kind: 'TEXT', required: false, position: 2 },
      { label: 'Disponibilité des matériaux', kind: 'OPTION', options: ['Matériaux déjà sur place', 'Fika doit chiffrer les matériaux', 'Partiellement disponible'], required: true, position: 3 },
    ],
    active: true,
    featured: false,
    popular: false,
    displayOrder: 3,
    budget: 'Moyen',
    delai: 'Standard',
    typeBesoin: 'Création',
    image: img('maison'),
    ...seo('Travaux de Maçonnerie', 'Construction, crépissage et gros œuvre à Ngaoundéré.'),
  },
  {
    id: 's-mai-4',
    slug: 'peinture-batiment',
    name: 'Peinture & Finition',
    categoryId: 'maison-travaux',
    shortDescription: 'Peinture intérieure, extérieure, enduit et rafraîchissement complet.',
    fullDescription: 'Redonnez vie à vos murs intérieurs et extérieurs. Les peintres du réseau Fika préparent les surfaces, appliquent les sous-couches et réalisent des finitions soignées et durables pour votre habitat ou local commercial.',
    priceType: 'PROJECT',
    startingPrice: undefined,
    deliveryIncluded: false,
    estimatedDuration: '1 à 4 jours selon surface',
    includedItems: ['Visite et évaluation des surfaces', 'Préparation des supports (rebouchage, ponçage)', 'Devis clair et transparent'],
    excludedItems: ['Seaux de peinture et consommables si non convenu'],
    requirements: [
      { label: 'Nombre de pièces ou surface approximative', kind: 'TEXT', required: true, position: 1 },
      { label: 'Zone concernée', kind: 'OPTION', options: ['Intérieur uniquement', 'Façade extérieure', 'Ensemble du bâtiment'], required: true, position: 2 },
    ],
    active: true,
    featured: false,
    popular: false,
    displayOrder: 4,
    budget: 'Moyen',
    delai: 'Standard',
    typeBesoin: 'Production',
    image: img('maison'),
    ...seo('Peinture Bâtiment', 'Peinture intérieure et extérieure soignée à Ngaoundéré.'),
  },
  {
    id: 's-mai-5',
    slug: 'menuiserie-bois-alu',
    name: 'Menuiserie Bois & Aluminium',
    categoryId: 'maison-travaux',
    shortDescription: 'Portes, fenêtres, placards, étagères et réparation de serrures/châssis.',
    fullDescription: 'Conception sur mesure ou réparation de vos éléments de menuiserie en bois massif ou aluminium vitré. Des artisans minutieux pour vos portes d\'entrée, baies vitrées, placards intégrés et réparations d\'huisseries.',
    priceType: 'PROJECT',
    startingPrice: undefined,
    deliveryIncluded: false,
    estimatedDuration: '2 à 5 jours selon commande',
    includedItems: ['Prise de cotes à domicile', 'Conseils sur les essences de bois et profilés alu', 'Pose et ajustement final'],
    excludedItems: ['Quincaillerie décorative spécifique'],
    requirements: [
      { label: 'Type d\'ouvrage souhaité (porte, placard, fenêtre, retouche)', kind: 'TEXT', required: true, position: 1 },
      { label: 'Matériau privilégié', kind: 'OPTION', options: ['Bois massif', 'Aluminium vitré', 'Panneau MDF / Contreplaqué', 'À conseiller par le pro'], required: true, position: 2 },
    ],
    active: true,
    featured: false,
    popular: false,
    displayOrder: 5,
    budget: 'Moyen',
    delai: 'Standard',
    typeBesoin: 'Création',
    image: img('maison'),
    ...seo('Menuiserie Bois et Alu', 'Conception et pose de menuiserie sur mesure à Ngaoundéré.'),
  },
  {
    id: 's-mai-6',
    slug: 'soudure-metallerie',
    name: 'Soudure & Métallerie',
    categoryId: 'maison-travaux',
    shortDescription: 'Portails, grilles antivol, garde-corps et réparations de ferronnerie.',
    fullDescription: 'Sécurisez votre propriété avec des structures métalliques solides et esthétiques. Fika missionne des soudeurs métalliers confirmés pour concevoir ou réparer vos portails, antivols de fenêtres, portes blindées et charpentes métalliques.',
    priceType: 'PROJECT',
    startingPrice: undefined,
    deliveryIncluded: false,
    estimatedDuration: '3 à 7 jours',
    includedItems: ['Relevé des dimensions sur place', 'Assemblage et soudure professionnelle', 'Traitement antirouille et pose'],
    excludedItems: [],
    requirements: [
      { label: 'Description de la structure (portail, antivol, grille...)', kind: 'TEXT', required: true, position: 1 },
      { label: 'Dimensions estimées (largeur x hauteur)', kind: 'TEXT', required: false, position: 2 },
    ],
    active: true,
    featured: false,
    popular: false,
    displayOrder: 6,
    budget: 'Moyen',
    delai: 'Standard',
    typeBesoin: 'Création',
    image: img('maison'),
    ...seo('Soudure et Métallerie', 'Portails, grilles antivol et ferronnerie à Ngaoundéré.'),
  },
  {
    id: 's-mai-7',
    slug: 'pose-carrelage',
    name: 'Carrelage & Revêtement Sol',
    categoryId: 'maison-travaux',
    shortDescription: 'Pose de carrelage sol et mural, faïence, terrasses et plinthes.',
    fullDescription: 'Sublimez vos sols et salles de bain. Les carreleurs du réseau Fika effectuent le ragréage, la pose droite ou diagonale, les découpes d\'angle soignées et la finition des joints pour un rendu durable.',
    priceType: 'PROJECT',
    startingPrice: undefined,
    deliveryIncluded: false,
    estimatedDuration: 'Selon surface (2 à 5 jours)',
    includedItems: ['Visite et prise de mesures sur place', 'Conseils calepinage et type de carreaux', 'Pose et jointoiement soigné'],
    excludedItems: ['Fourniture des carreaux et colle'],
    requirements: [
      { label: 'Surface approximative en m² ou nombre de pièces', kind: 'TEXT', required: true, position: 1 },
      { label: 'Type d\'espace (salon, salle de bain, terrasse)', kind: 'TEXT', required: true, position: 2 },
    ],
    active: true,
    featured: false,
    popular: false,
    displayOrder: 7,
    budget: 'Moyen',
    delai: 'Standard',
    typeBesoin: 'Création',
    image: img('maison'),
    ...seo('Carrelage et Revêtement', 'Pose de carrelage, faïence et dallage à Ngaoundéré.'),
  },
  {
    id: 's-mai-8',
    slug: 'toiture-charpente',
    name: 'Toiture & Étanchéité',
    categoryId: 'maison-travaux',
    shortDescription: 'Réparation de fuite de toit, tôles ondulées, charpente bois/métal et étanchéité.',
    fullDescription: 'Protégez votre bâtiment des intempéries. Fika fait intervenir des charpentiers-couvreurs pour réparer les fuites de toiture, remplacer des tôles endommagées ou rénover complètement votre toiture.',
    priceType: 'PROJECT',
    startingPrice: undefined,
    deliveryIncluded: false,
    estimatedDuration: '1 à 3 jours selon dégâts',
    includedItems: ['Inspection en toiture et diagnostic infiltration', 'Devis détaillé main-d\'œuvre et matériaux', 'Réparation et fixation étanche'],
    excludedItems: ['Achat des tôles, pointes ou goudron d\'étanchéité'],
    requirements: [
      { label: 'Problème constaté (fuite, tôle envolée, rénovation)', kind: 'TEXT', required: true, position: 1 },
      { label: 'Type de bâtiment et quartier', kind: 'TEXT', required: true, position: 2 },
    ],
    active: true,
    featured: false,
    popular: false,
    displayOrder: 8,
    budget: 'Moyen',
    delai: 'Standard',
    typeBesoin: 'Création',
    image: img('maison'),
    ...seo('Toiture et Étanchéité', 'Réparation toiture, tôles et fuite d\'eau à Ngaoundéré.'),
  },

  /* =======================================================================
   * 2. RÉPARATION & MAINTENANCE
   * ======================================================================= */
  {
    id: 's-rep-1',
    slug: 'reparation-telephone',
    name: 'Réparation Téléphone & Tablette',
    categoryId: 'reparation-maintenance',
    shortDescription: 'Écran cassé, remplacement de batterie, connecteur de charge et logiciel.',
    fullDescription: 'Votre smartphone ou tablette est tombé en panne ? Confiez-le à Fika. Nous collectons l\'appareil, faisons diagnostiquer la panne par un technicien de notre réseau, validons le devis avec vous et vous le restituons réparé.',
    priceType: 'DIAGNOSTIC',
    startingPrice: null,
    deliveryIncluded: false,
    estimatedDuration: '24 à 48 heures',
    includedItems: ['Collecte et retour de l\'appareil organisés par Fika', 'Diagnostic complet en atelier', 'Devis ferme avant réparation, validé avec vous'],
    excludedItems: ['Coût de l\'écran neuf ou de la batterie'],
    requirements: [
      { label: 'Marque et modèle exact (ex: Samsung A12, iPhone 11, Tecno Spark)', kind: 'TEXT', required: true, position: 1 },
      { label: 'Symptômes de la panne (ne s\'allume plus, écran fissuré, ne charge pas)', kind: 'TEXT', required: true, position: 2 },
    ],
    active: true,
    featured: true,
    popular: true,
    displayOrder: 1,
    budget: 'Faible',
    delai: 'Rapide',
    typeBesoin: 'Intervention',
    image: img('reparation'),
    ...seo('Réparation Téléphone', 'Écran cassé, batterie, connecteur smartphone à Ngaoundéré.'),
  },
  {
    id: 's-rep-2',
    slug: 'reparation-electromenager',
    name: 'Dépannage Électroménager & Climatisation',
    categoryId: 'reparation-maintenance',
    shortDescription: 'Réfrigérateur, congélateur, climatiseur, machine à laver, micro-ondes.',
    fullDescription: 'Un appareil indispensable qui vous lâche ? Décrivez le symptôme, Fika dépêche un frigoriste ou dépanneur électroménager à domicile pour inspecter le compresseur, thermostat ou moteur et réparer sur place.',
    priceType: 'DIAGNOSTIC',
    startingPrice: null,
    deliveryIncluded: false,
    estimatedDuration: 'Intervention sous 24h',
    includedItems: ['Déplacement du technicien organisé par Fika (intégré au devis)', 'Recherche de panne sur l\'appareil', 'Devis clair pour la réparation'],
    excludedItems: ['Gaz frigorigène ou pièces détachées de rechange'],
    requirements: [
      { label: 'Type d\'appareil et marque (ex: Congélateur Hisense, Split Samsung)', kind: 'TEXT', required: true, position: 1 },
      { label: 'Panne constatée (ne refroidit plus, fuite d\'eau, disjoncte)', kind: 'TEXT', required: true, position: 2 },
    ],
    active: true,
    featured: true,
    popular: false,
    displayOrder: 2,
    budget: 'Faible',
    delai: 'Standard',
    typeBesoin: 'Intervention',
    image: img('reparation'),
    ...seo('Dépannage Électroménager', 'Frigo, congélateur, clim et électroménager à Ngaoundéré.'),
  },
  {
    id: 's-rep-3',
    slug: 'reparation-informatique',
    name: 'Dépannage Ordinateur & Imprimante',
    categoryId: 'reparation-maintenance',
    shortDescription: 'PC portable lent, écran noir, formatage, nettoyage virus, imprimante bloquée.',
    fullDescription: 'Votre outil de travail fait des siennes ? Problème de disque dur, système d\'exploitation Windows/Mac bloqué, chargeur défectueux ou bourrage imprimante : Fika prend en charge la remise en état de votre matériel informatique.',
    priceType: 'DIAGNOSTIC',
    startingPrice: null,
    deliveryIncluded: false,
    estimatedDuration: '24 à 48 heures',
    includedItems: ['Diagnostic matériel et logiciel', 'Sauvegarde préalable de vos fichiers si possible', 'Rapport de test après réparation'],
    excludedItems: ['Composants de remplacement (SSD, RAM, écran)'],
    requirements: [
      { label: 'Type de matériel (PC portable, unité centrale, imprimante)', kind: 'TEXT', required: true, position: 1 },
      { label: 'Description du problème rencontré', kind: 'TEXT', required: true, position: 2 },
    ],
    active: true,
    featured: false,
    popular: false,
    displayOrder: 3,
    budget: 'Faible',
    delai: 'Rapide',
    typeBesoin: 'Intervention',
    image: img('reparation'),
    ...seo('Dépannage Informatique', 'Réparation PC portable, écran, formatage et imprimante à Ngaoundéré.'),
  },

  /* =======================================================================
   * 3. AUTO & MOTO
   * ======================================================================= */
  {
    id: 's-aut-1',
    slug: 'depannage-mecanique-auto',
    name: 'Dépannage & Entretien Auto',
    categoryId: 'auto-moto',
    shortDescription: 'Panne de démarrage, diagnostic moteur, vidange, freins et électricité auto.',
    fullDescription: 'Votre voiture refuse de démarrer, chauffe ou présente un bruit suspect ? Fika missionne un mécanicien ou électricien automobile compétent sur les lieux de la panne ou chez vous pour un diagnostic immédiat et une remise en route.',
    priceType: 'DIAGNOSTIC',
    startingPrice: null,
    deliveryIncluded: false,
    estimatedDuration: 'Intervention sous 1h à 4h',
    includedItems: ['Déplacement du mécanicien organisé par Fika (intégré au devis)', 'Diagnostic panne ou check-up moteur', 'Devis précis avant toute réparation'],
    excludedItems: ['Huile de vidange, filtres et pièces mécaniques'],
    requirements: [
      { label: 'Marque et modèle du véhicule (ex: Toyota Corolla, RAV4)', kind: 'TEXT', required: true, position: 1 },
      { label: 'Description de la panne ou du besoin', kind: 'TEXT', required: true, position: 2 },
      { label: 'Localisation exacte à Ngaoundéré', kind: 'TEXT', required: true, position: 3 },
    ],
    active: true,
    featured: true,
    popular: false,
    displayOrder: 1,
    budget: 'Moyen',
    delai: 'Rapide',
    typeBesoin: 'Intervention',
    image: img('auto-moto'),
    ...seo('Dépannage Mécanique Auto', 'Mécanicien automobile à domicile et sur route à Ngaoundéré.'),
  },
  {
    id: 's-aut-2',
    slug: 'depannage-moto',
    name: 'Entretien & Réparation Moto',
    categoryId: 'auto-moto',
    shortDescription: 'Vidange, carburation, transmission, freins, électricité et révision deux-roues.',
    fullDescription: 'Une panne de moto en pleine circulation ou besoin d\'une révision complète ? Fika vous oriente vers un atelier partenaire de confiance ou envoie un mécanicien moto pour remettre votre deux-roues en parfait état de marche.',
    priceType: 'DIAGNOSTIC',
    startingPrice: null,
    deliveryIncluded: false,
    estimatedDuration: 'Intervention rapide le jour même',
    includedItems: ['Diagnostic carburation et transmission', 'Contrôle des freins et sécurité', 'Main-d\'œuvre de révision'],
    excludedItems: ['Pièces et consommables (bougie, huile, plaquettes)'],
    requirements: [
      { label: 'Type et marque de moto (ex: Boxer, Sanili, TVS, Yamaha)', kind: 'TEXT', required: true, position: 1 },
      { label: 'Problème observé', kind: 'TEXT', required: true, position: 2 },
    ],
    active: true,
    featured: false,
    popular: false,
    displayOrder: 2,
    budget: 'Faible',
    delai: 'Rapide',
    typeBesoin: 'Intervention',
    image: img('auto-moto'),
    ...seo('Entretien et Réparation Moto', 'Mécanique deux-roues et dépannage moto à Ngaoundéré.'),
  },

  /* =======================================================================
   * 4. TRANSPORT & LOGISTIQUE
   * ======================================================================= */
  {
    id: 's-tra-1',
    slug: 'demenagement-local',
    name: 'Déménagement Local & Transport',
    categoryId: 'transport-logistique',
    shortDescription: 'Transport de meubles, cartons, chargement et déchargement sécurisés.',
    fullDescription: 'Organisez votre déménagement à Ngaoundéré l\'esprit léger. Fika affrète le véhicule adapté (tricycle à benne, camionnette ou camion benne) et organise l\'équipe de manutentionnaires pour charger, transporter et décharger vos biens sans risque.',
    priceType: 'QUOTE',
    startingPrice: null,
    deliveryIncluded: false,
    estimatedDuration: 'Demi-journée à 1 journée',
    includedItems: ['Véhicule adapté selon volume', 'Chauffeur et carburant inclus', 'Manutentionnaires pour le portage'],
    excludedItems: ['Fourniture de cartons d\'emballage'],
    requirements: [
      { label: 'Quartier de départ', kind: 'TEXT', required: true, position: 1 },
      { label: 'Quartier d\'arrivée', kind: 'TEXT', required: true, position: 2 },
      { label: 'Volume estimé et meubles lourds (lit, frigo, armoire)', kind: 'TEXT', required: true, position: 3 },
    ],
    active: true,
    featured: true,
    popular: true,
    displayOrder: 1,
    budget: 'Moyen',
    delai: 'Standard',
    typeBesoin: 'Intervention',
    image: img('transport'),
    ...seo('Déménagement Local', 'Déménagement et transport de meubles sans stress à Ngaoundéré.'),
  },
  {
    id: 's-tra-2',
    slug: 'livraison-courses-express',
    name: 'Courses & Livraison Express',
    categoryId: 'transport-logistique',
    shortDescription: 'Récupération de colis, plis urgents, courses de marché et achats en ville.',
    fullDescription: 'Pas le temps de courir en ville ? Fika envoie un coursier fiable pour récupérer vos colis à l\'agence de voyage, faire une course urgente au grand marché ou livrer un document à votre place dans toute la ville.',
    priceType: 'QUOTE',
    startingPrice: null,
    deliveryIncluded: false,
    estimatedDuration: 'Moins de 60 minutes',
    includedItems: ['Prise en charge immédiate', 'Transport rapide en deux-roues', 'Confirmation de remise en main propre'],
    excludedItems: ['Montant des achats à régler au commerçant'],
    requirements: [
      { label: 'Nature de la course ou contenu du pli', kind: 'TEXT', required: true, position: 1 },
      { label: 'Lieu de retrait', kind: 'TEXT', required: true, position: 2 },
      { label: 'Lieu de destination', kind: 'TEXT', required: true, position: 3 },
    ],
    active: true,
    featured: false,
    popular: false,
    displayOrder: 2,
    budget: 'Faible',
    delai: 'Rapide',
    typeBesoin: 'Intervention',
    image: img('transport'),
    ...seo('Courses et Livraison Express', 'Coursier rapide et livraison de plis/colis à Ngaoundéré.'),
  },

  /* =======================================================================
   * 5. NUMÉRIQUE & DOCUMENTS
   * ======================================================================= */
  {
    id: 's-num-1',
    slug: 'creation-cv-professionnel',
    name: 'CV & Lettre de Motivation Pro',
    categoryId: 'numerique-documents',
    shortDescription: 'Mise en valeur de votre parcours, design moderne et format PDF prêt à postuler.',
    fullDescription: 'Multipliez vos chances de décrocher un emploi ou un stage. Nous restructurons votre parcours, rédigeons des accroches percutantes et soignons la mise en page graphique pour un dossier de candidature irréprochable.',
    priceType: 'FIXED',
    startingPrice: 3000,
    deliveryIncluded: true,
    estimatedDuration: '24 à 48 heures',
    includedItems: ['Restructuration et correction orthographique', 'Design graphique moderne et épuré', 'Fichiers finaux PDF haute définition et Word modifiable'],
    excludedItems: ['Impression papier (disponible en option)'],
    requirements: [
      { label: 'Parcours, diplômes et expériences clés', kind: 'TEXT', required: true, position: 1 },
      { label: 'Intitulé du poste ou profil visé', kind: 'TEXT', required: true, position: 2 },
    ],
    active: true,
    featured: true,
    popular: false,
    displayOrder: 1,
    budget: 'Faible',
    delai: 'Rapide',
    typeBesoin: 'Production',
    image: img('numerique'),
    ...seo('Création de CV Professionnel', 'CV moderne et lettre de motivation percutante à Ngaoundéré.'),
  },
  {
    id: 's-num-2',
    slug: 'bureautique-impression',
    name: 'Impression, Reliure & Saisie',
    categoryId: 'numerique-documents',
    shortDescription: 'Impression noir & couleur, reliure de rapports/mémoires et saisie de documents.',
    fullDescription: 'Envoyez simplement vos fichiers PDF ou photos de manuscrits par WhatsApp. Fika réalise l\'impression haute qualité, la reliure plastique ou thermique soignée et vous livre le document relié directement chez vous ou au bureau.',
    priceType: 'FROM',
    startingPrice: 500,
    deliveryIncluded: true,
    estimatedDuration: 'Livraison le jour même',
    includedItems: ['Vérification des marges et mise en page', 'Impression papier qualité laser', 'Livraison directe à domicile'],
    excludedItems: [],
    requirements: [
      { label: 'Nombre de pages et description du document', kind: 'TEXT', required: true, position: 1 },
      { label: 'Type d\'impression', kind: 'OPTION', options: ['Noir & Blanc', 'Couleur', 'Mixte'], required: true, position: 2 },
      { label: 'Reliure souhaitée ?', kind: 'OPTION', options: ['Sans reliure (agrafé)', 'Reliure spirale plastique', 'Reliure thermique'], required: false, position: 3 },
    ],
    active: true,
    featured: false,
    popular: false,
    displayOrder: 2,
    budget: 'Faible',
    delai: 'Rapide',
    typeBesoin: 'Production',
    image: img('numerique'),
    ...seo('Impression et Reliure', 'Impression de rapports, mémoires et livraison à domicile à Ngaoundéré.'),
  },
  {
    id: 's-num-3',
    slug: 'presence-digitale-pro',
    name: 'Site Vitrine & Présence Google',
    categoryId: 'numerique-documents',
    shortDescription: 'Site web mobile rapide, fiche Google Maps vérifiée et catalogue WhatsApp Business.',
    fullDescription: 'Augmentez la crédibilité de votre activité commerciale ou de votre PME à Ngaoundéré. Fika crée votre site vitrine clé en main, référence votre enseigne sur Google Maps et structure votre profil WhatsApp Business pour convertir vos prospects.',
    priceType: 'FROM',
    startingPrice: 25000,
    deliveryIncluded: false,
    estimatedDuration: '3 à 5 jours ouvrés',
    includedItems: ['Création de la page vitrine responsive', 'Fiche Google Business / Maps optimisée', 'Boutons d\'action WhatsApp direct'],
    excludedItems: ['Nom de domaine personnalisé .com/.cm (facturé au coût réel si requis)'],
    requirements: [
      { label: 'Nom de l\'activité et secteur commercial', kind: 'TEXT', required: true, position: 1 },
      { label: 'Numéro WhatsApp de contact', kind: 'TEXT', required: true, position: 2 },
      { label: 'Photos et logo si déjà disponibles', kind: 'FILE', required: false, position: 3 },
    ],
    active: true,
    featured: false,
    popular: false,
    displayOrder: 3,
    budget: 'Moyen',
    delai: 'Standard',
    typeBesoin: 'Création',
    image: img('numerique'),
    ...seo('Site Vitrine et Présence Google', 'Création de site internet et visibilité Google à Ngaoundéré.'),
  },

];

export const UNIVERSE_PACKAGES: Package[] = [
  // Règle : un pack n'existe que si CHAQUE ligne a un prix standard réel
  // (validatePriceConsistency). Les interventions et travaux restent au devis.
  {
    id: 'pkg-lancement-commerce',
    slug: 'pack-visibilite-commerce',
    title: 'Pack Visibilité Commerce',
    description: 'Site web vitrine + fiche Google Maps + dossier de présentation + 10 impressions de supports commerciaux.',
    price: 30000,
    categoryId: 'numerique-documents',
    active: true,
    services: [
      { serviceId: 's-num-3', quantity: 1, customName: 'Site vitrine & Fiche Google Maps' },
      { serviceId: 's-num-1', quantity: 1, customName: 'Dossier de présentation' },
      { serviceId: 's-num-2', quantity: 10, customName: 'Impression documents commerciaux' },
    ],
  },
];

export const CITY_PRICES: CityPricing[] = [];

export const getServiceRef = (id: string): Service | undefined =>
  SERVICES.find((s) => s.id === id);

export const POPULAR_ORDER = [
  'intervention-plomberie',
  'intervention-electricite',
  'reparation-telephone',
  'demenagement-local',
];
